MyFollow/Controllers/EndUserController.cs
using System.Linq;
using System.Web.Mvc;
using MyFollow.DAL;
using System.Net;
using MyFollow.Models;

namespace MyFollow.Controllers
{
    public class EndUserController : Controller
    {
        private MyFollowContext db = new MyFollowContext();

       [Authorize(Roles = "User")]
        public ActionResult ViewPages()
        {
            //ViewBag.Email = email;
            return View();
        }

       [Authorize(Roles = "User")]
        public ActionResult Index()
        {
            //ViewBag.Email = email;
            return View();
        }

        [Authorize(Roles = "User")]
        public ActionResult ProductsList()
        {
            return View(db.Productses.ToList());
        }

         [Authorize(Roles = "User")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Productses.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            ViewBag.ImageList = db.UploadImageses.ToList().Where(a => a.ProductId == products.Id);
            return View(products);
        }
    }
}

MyFollow/Controllers/ProductOwnersController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using MyFollow.DAL;
using MyFollow.Models;
using System.Net;
using System.Data.Entity;

namespace MyFollow.Controllers
{
    [Authorize(Roles="ProductOwner")]
    public class ProductOwnersController : Controller
    {
        private MyFollowContext db = new MyFollowContext();

        public ProductOwnersController()
        {
        }
        public ProductOwnersController(ApplicationUserManager userManager,  ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }


        // GET: ProductOwners
        public ActionResult Index(string email)
        {
            Session["Email"] = email;
            var product = db.ProductOwners.FirstOrDefault(x => x.EmailId == email);
            if(product != null)
            { 
                ViewBag.Id = product.Id;
            }
            return View();
        }

        // GET: ProductOwners/Details/5
        public ActionResult Details(string email)
        {
            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session["Email"] = email;
            ProductOwner productOwner = db.ProductOwners.FirstOrDefault(x => x.EmailId == email);
            if (productOwner == null)
            {
                return HttpNotFound();
            }
            return View(productOwner);
        }

        // GET: ProductOwners/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: ProductOwners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "Id,CompanyName,EmailId,Description,DateofJoin,FoundedIn,Street1,Street2,City,State,Country,Pincode,ContactNumber,Website,Twitter,Facebook,Password,ApprovalFlag")] ProductOwner productOwner)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.ProductOwners.Add(productOwner);
        //        db.SaveChanges();
        //        var user = new ApplicationUser { UserName = productOwner.EmailId, Email = productOwner.EmailId };
        //        var result = await UserManager.CreateAsync(user, productOwner.Password);
        //        if (result.Succeeded)
        //        {
        //            var code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
        //            await UserManager.AddToRolesAsync(user.Id, "ProductOwner");
        //        }

        //        return RedirectToAction("Index");
        //    }

        //    return View(productOwner);
        //}

        // GET: ProductOwners/Edit/5
        public ActionResult Edit()
        {
            if (Session["Email"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string email = Session["Email"].ToString();
            ProductOwner productOwner = db.ProductOwners.FirstOrDefault(x => x.EmailId == email);
            if (productOwner == null)
            {
                return HttpNotFound();
            }
            return View(productOwner);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( ProductOwner productOwner)
        {
            if (ModelState.IsValid)
            {
                productOwner.EmailId = Session["Email"].ToString();
                db.Entry(productOwner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new {Email=Session["Email"] });
            }
            return View(productOwner);
        }

        // GET: ProductOwners/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ProductOwner productOwner = db.ProductOwners.Find(id);
        //    if (productOwner == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(productOwner);
        //}

        //// POST: ProductOwners/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    ProductOwner productOwner = db.ProductOwners.Find(id);
        //    db.ProductOwners.Remove(productOwner);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyFollow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html data-ng-app="AppRoute">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Follow</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Follow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @*<li>@Html.ActionLink("ProductOwner", "Create", "ProductOwners")</li>
                        <li>@Html.ActionLink("Products", "Create", "Products")</li>*@

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Follow</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angularjs")
    @*@Scripts.Render("~/bundles/AngularRoute")
    @Scripts.Render("~/bundles/AppRoute")
    <script src="~/Scripts/knockout-2.0.0.debug.js"></script>
    <script src="~/Scripts/multi-uploader.js"></script>*@

   @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
 

</body>
</html>

MyFollow/Views/Shared/_LayoutPageAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Follow</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Follow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Index", "Index", "Account")</li>
                    <li>@Html.ActionLink("Owner List", "AllProductOwner", "Account")</li>
                    @*<li>@Html.ActionLink("Update Products", "Index", "Products")</li>
                    <li>@Html.ActionLink("Edit Profile", "Edit", "ProductOwners")</li>*@

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Follow</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
   @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</body>
</html>

MyFollow/Views/Shared/_LayoutPageEndUser.cshtml
<!DOCTYPE html>
<html data-ng-app="AppRoute">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Follow</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Follow", "Index", "EndUser", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li>@Html.ActionLink("Home", "ViewPages", "EndUser")</li>
                       @*   <li>@Html.ActionLink("About", "About", "Home")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    @*<li>@Html.ActionLink("ProductOwner", "Create", "ProductOwners")</li>
        <li>@Html.ActionLink("Products", "Create", "Products")</li>*@
                    <li data-ng-app data-ng-controller="EndUserController"><a href="#/ListProductData">List Products</a></li>
                    <li data-ng-app data-ng-controller="EndUserController"><a href="#/ListFollowProducts">Follow Products</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Follow</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/angularjs")
    @Scripts.Render("~/bundles/AngularRoute")
    @Scripts.Render("~/bundles/AppRoute")
    <script src="~/Scripts/knockout-2.0.0.debug.js"></script>
    <script src="~/Scripts/multi-uploader.js"></script>
</body>
</html>

MyFollow/Views/Shared/_LayoutPageProductOwner.cshtml
<!DOCTYPE html>
<html data-ng-app="AppRoute">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Follow</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Follow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Index", "Index", "ProductOwners")</li>
        <li>@Html.ActionLink("Add Product", "Create", "Products")</li>
        <li>@Html.ActionLink("Update Products", "Index", "Products")</li>
        <li>@Html.ActionLink("Edit Profile", "Edit", "ProductOwners")</li>
    <li>@Html.ActionLink("Home", "Index", "ProductOwners")</li*@
                    <li data-ng-app data-ng-controller="ProductController"><a href="#/AddNewMainProduct/@ViewBag.Id">Add Product</a></li>
                    <li data-ng-app data-ng-controller="ProductController"><a href="#/AddNewProduct/@ViewBag.Id">Add Product Update</a></li>
                    <li data-ng-app data-ng-controller="ProductController"><a href="#/ListProduct/@ViewBag.Id" >List Products</a></li>
                    <li data-ng-app data-ng-controller="ProductOwnerController" ><a  href="#/EditProductOwner/@ViewBag.Id">Edit Profile</a></li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
                
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Follow</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angularjs")
    @Scripts.Render("~/bundles/AngularRoute")
    @Scripts.Render("~/bundles/AppRoute")
    <script src="~/Scripts/knockout-2.0.0.debug.js"></script>
    <script src="~/Scripts/multi-uploader.js"></script>

</body>
</html>